### ISSUE TITLE
only 1 range circle at a time

### ISSUE THREAD

**Issue by beringtom** [Endebert/squadmc#15]
Hello.

When placing down mortars it shows the range circle fine on the first, then when you place another one in another color the circle switches to the new placed mark.

To get the first range shown again you need to change the size of the icons.

(happends on squad and PS if they are unconnected)

**Comment by Endebert** [comment]
Thanks for the feedback. This is actually intended, as I felt it to be too confusing to have all range circles being shown at the same time.

I didn't expect anyone wanting this, but since you created this issue and implementation was very easy, I added this as an option to the map settings. 

It's currently pushed to the dev branch, check it out here: https://dev.squadmc.ende.pro/

Tomorrow I'll merge the changes into master and postscriptum branch

**Comment by beringtom** [comment]
I actually use it in PS as there is no "meta" yet, so I use it to figure out where i can setup mortars as shown on the picture. Where the circles overlap i can place mortars and hit both targets.

![screenshot_18](https://user-images.githubusercontent.com/3480271/41187395-86f7f9ca-6ba8-11e8-8ff4-e490c79b3158.png)
