### ISSUE TITLE
Oosterbeek map grid need slight correction

### ISSUE THREAD

**Issue by Valpra** [Endebert/squadmc#20]
I have some  slight problems using psmc on  map Oosterbeek. Map image position need correction with the grid. Look at the picture.
http://funkyimg.com/i/2JmeL.png

**Comment by Endebert** [comment]
great find, thanks for letting me know.

Would you be so kind and make a screenshot of the fully zoomed out map ingame, please? Like in this screenshot: 

![minimap screenshot](https://user-images.githubusercontent.com/3480271/40611578-2c5fb406-6277-11e8-8a05-4e311fcc8e77.png
)
I just want to double-check if the map dimensions have changed

**Comment by Valpra** [comment]
Beta servers is not active now. So i wrote "AdminChangeMap Oosterbeek Single 01" in console to load map. 
http://funkyimg.com/i/2JszR.jpg

**Comment by Endebert** [comment]
@Valpra Thank you very much for your feedback. Both the comparison image, and the high-res map screenshot were very helpful in solving this issue. As you can see in the referenced commit, I updated the map bounds, which resulted in a grid that is closer to the one ingame.

The problem was that the grid is not perfectly rectangular for the map, which I assumed.

I found a similar issue for Driel after double-checking the other maps, and will update its bounds as well.

Thanks again for your efforts.
