### ISSUE TITLE
Need update!

### ISSUE THREAD

**Issue by istanbuls** [Endebert/squadmc#27]
Need update of the name and locations of the cities.

**Comment by nonsintetic** [comment]
Gorodok is missing Boris Farmstead for example

**Comment by Endebert** [comment]
I'm currently working on a large refactor of the app on weekends. I'm planning to introduce a mode that will allow people to place location markers themselves and export them to be posted here and integrated into the application by me.

Unfortunately, this will probably take a few more weeks.

**Comment by Endebert** [comment]
Locations are very annoying to add (you have to run squadmc in dev mode, place a marker, get the marker coordinates from the console output, then add the location to the corresponding map in squadmc-maps, like so: https://github.com/Endebert/squadmc-maps/blob/master/public/mapdata.js#L9-L20

If someone wants to go through that hassle, be my guest, but I'll not invest the time, as I don't use the location layer myself (because it's so outdated)
