### ISSUE TITLE
Map updates/USA forces to add

### ISSUE THREAD

**Issue by Cluster04** [Endebert/squadmc#37]
Are maps and usa mortor going to be updated.

**Comment by TopMak** [comment]
Hey!

I'm the guy who has updated most the PS maps for this branch. I haven't been playing the game for a while. Could you tell me, what maps has been changed?
I'll take a look if there has been any "gamebreaking" changes.

I know they are going to release a new map soon, so I'll try to push the update for it also once it's been implemented to the game. 

I actually had the patch ready for adding the USA mortar button to the interface, but I forgot to push it, since I was waiting if they are changing the ranging on it. 😅  (At least at the release time of Velmolen, it was the same as British one).

**Comment by fjod** [comment]
al basrah map slightly outdated, they added another "street" with buildings north part of the city

**Comment by Endebert** [comment]
I believe this can be closed. Please reopen if that's not the case.
