### ISSUE TITLE
Post Scriptum Support

### ISSUE THREAD

**Issue by beringtom** [Endebert/squadmc#8]
Would love to see you add Post scriptum maps to your lovely little calculator.

**Comment by beringtom** [comment]
Download links for exported minimap files.
[Heelsum_Gameplay_Minimap](http://beringtom.dk/psmaps/Heelsum_Gameplay_Minimap.png)
[Johanna_Gameplay_Minimap](http://beringtom.dk/psmaps/Johanna_Gameplay_Minimap.png)
[Driel_Gameplay_Minimap](http://beringtom.dk/psmaps/Driel_Gameplay_Minimap.png)

**Comment by Endebert** [comment]
Unfortunately, I do not own Post Scriptum myself. I'm assuming it has mortars as well? 

First, I need some information about the map dimensions. In the beginning of the project, I just used the ingame minimap, which should work for now. Could you maybe provide those?

[Something like this.](https://raw.githubusercontent.com/Endebert/squadmc/23c54d1a42d9e44f0bd5ddbdf97ede795647c187/public/maps/kohat_l.jpg)

I'd need a screenshot of a fully zoomed out minimap from ingame with the grid, so I can calculate the map dimensions. Not very accurate, but the only way, since there doesn't seem to be a SDK for the game.

Other than that, I don't know if its mortars work differently, so that could be an issue as well. Do they have a meter<->mil table like in squad?

**Comment by beringtom** [comment]
![skaermbillede 2018-05-28 12 40 37](https://user-images.githubusercontent.com/3480271/40611578-2c5fb406-6277-11e8-8a05-4e311fcc8e77.png)
![skaermbillede 2018-05-28 12 54 19](https://user-images.githubusercontent.com/3480271/40611579-2c7b93f6-6277-11e8-9f88-466a0056dc11.png)
![skaermbillede 2018-05-28 12 54 57](https://user-images.githubusercontent.com/3480271/40611580-2c967fc2-6277-11e8-8b9d-22a0aa779865.png)

**Comment by beringtom** [comment]
![skaermbillede 2018-05-28 13 03 18](https://user-images.githubusercontent.com/3480271/40611770-f8b74c4e-6277-11e8-9bf1-712841bd2996.png)
![skaermbillede 2018-05-28 13 06 20](https://user-images.githubusercontent.com/3480271/40611771-f8d1a062-6277-11e8-9b76-be1c7dbb54f7.png)

**Comment by Endebert** [comment]
Thanks for the screenshots, I'm almost ready with the redesign for SquadMC. Once that is published I will fork it and prepare a version with Post Scriptum.

**Comment by Endebert** [comment]
Aaand its done. Check here for the current version: https://postscriptum.squadmc.ende.pro/

Please test it to see if the mortar ranges are correct. They are based on the table you provided and should be relatively accurate, unless they changed the trajectory algorithm (doesn't look like it though).

Of course, no heightmaps, so please test on flat terrain.

Closing this unless errors are reported.
